### ISSUE TITLE
using language model (ESM) to predict transmembrane proteins

### ISSUE THREAD

**Issue by wangleiofficial** [BernhoferM/TMbed#1]
hello, Michael Bernhofer
DeepTMpred (https://www.sciencedirect.com/science/article/pii/S2001037022001428) should be the first tool to use a language model (ESM) to predict transmembrane proteins, if possible, you can add this method to the comparison, thank you very much!

**Comment by BernhoferM** [comment]
Dear Lei Wang,
Unfortunately, we have not been aware of your method when working on the manuscript. Since the manuscript has already been accepted and published, we cannot add your method to our comparisons anymore. However, we have not claimed to be the first method to use pLMs for transmembrane protein prediction (if that is your concern). In fact, we specifically refer to DeepTMHMM (pre-print: https://doi.org/10.1101/2022.04.08.487609), another method that uses a pLM (ESM-1b).

Regards
Michael Bernhofer

**Comment by wangleiofficial** [comment]
@BernhoferM  Congratulations that your manuscript has been accepted, your tool has been compared to DeepTMHMM, but its paper is also later than DeepTMpred. If possible, you can add an introduction of DeepTMpred to the preprint paper, thanks again!

**Comment by BernhoferM** [comment]
The bioRxiv preprint cannot be changed either. Their FAQ states: "An article posted on bioRxiv can be revised at any time, until it is accepted for publication." Since it has been accepted and published, the preprint should not be changed.

Regards
Michael Bernhofer
