### ISSUE TITLE
Training on only alpha helical proteins

### ISSUE THREAD

**Issue by sirius777coder** [BernhoferM/TMbed#10]
Hi, 

I really appreciate your work and code, and I have a question about the training process. My dataset only consists of alpha-helical proteins and I want to use your model to fine-tune the alpha-helical membrane prediction. Can I just run your vertibi decoding alrotithm and don't change anything else? As my dataset doesn't have beta-strand and I don't use In->OUT orientation. Thanks!

**Comment by BernhoferM** [comment]
Hi,

as described in the paper, the Viterbi decoder was not used during training; only afterwards for finding the best path according to the predicted probabilities. Thus, if you want to fine-tune the model, you'd simply train the Predictor model (CNN plus Gaussian filter) using the standard CrossEntropyLoss.

However, the current Viterbi decoder expects five predicted state probabilities: beta-strand, alpha-helix, signal peptide, inside, and outside. Unless your fine-tuned model provides those as well, you'll have to adjust the decoder (transitions) accordingly. Especially as the inside/outside states are used to define membrane boundaries by requiring a change in topology after each membrane segment. That being said, if your data set does not include beta-strands and inside/outside annotations, you're reducing the model from 5 to 3 states (2 if you also do not have signal peptides), with one state being "new" (non-membrane instead of IN/OUT). I'm not sure if fine-tuning is doing much at this point or if training the model from scratch might be the better choice.

**Comment by sirius777coder** [comment]
Thaks for your kind reply! I will try this.

**Comment by sirius777coder** [comment]
Hi, I'm also curious about the GaussianFilter. Did you include it during training or only in the inference stage?
