### ISSUE TITLE
Working with multiple GPUs on a single machine

### ISSUE THREAD

**Issue by yuddecho** [BernhoferM/TMbed#7]
Hi,  I have 4 GPUs with a single size of 7GB. When I use 'tmbed embed --use-gpu -f ./ch/test.fasta -e test.h5', it prompts that the GPU is out of memory.
How can 4 GPUs participate in the work simultaneously

**Comment by BernhoferM** [comment]
Hi. Unfortunately, I do not have any experience with a multi-GPU environment. Assuming you are already using a batch size of 1 to process each sequence individually, splitting the data processing won't help much (I do not think that there is any benefit in splitting the computation of individual layers of the model onto multiple GPUs).

One solution that would come to mind is pooling the GPUs' memory into one big chunk of memory. However, I do not know how exactly this would be done; and it might not be possible/feasible without a NVLink connection (or similar) between the GPUs.

Another solution would be to modify the attention mechanism, which due to its squared complexity is the culprit for many out of memory errors. However, this would mean modifying the Huggingface model (T5EncoderModel), i.e., rewriting a modified Pytorch Module that can load the pretrained weights. The calculation of the attention mechanism could then be split into processing each query (residue) individually, rather than all at once. Though, I'd guess that this would increase the runtime by quite a lot.

Finally, you could try to run the T5EncoderModel in 8-bit mode. Though, I do not know how much of an impact that would have on the prediction accuracy. See: https://huggingface.co/docs/transformers/perf_infer_gpu_one

With that being said, before you try any of those solutions, you might want to consider running your sequences in Google Colab (if there are no issues regarding data security). A free account usually gets you a GPU with 16GB of memory and about an hour of runtime.

Regards
Michael

**Comment by yuddecho** [comment]
Hi. Thank you for your reply. The final solution is to manually allocate data. I have a total of 20W of data, which is divided into 4 parts on average and assigned separately:

CUDA_VISIBLE_DEVICES=0 nohup python -m tmbed embed --batch-size 1000 -f ~/protein/data0.fasta -e ~/protein/data0.h5 > ~/protein/data0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python -m tmbed embed --batch-size 1000 -f ~/protein/data1.fasta -e ~/protein/data1.h5 > ~/protein/data1.log 2>&1 &
......

then 

CUDA_VISIBLE_DEVICES=0 nohup python -m tmbed predict --batch-size 5000 -f ~/protein/data0.fasta -e ~/protein/data0.h5 -p ~/protein/ch/data0.pred > ~/protein/data0.log 2>&1 &
CUDA_VISIBLE_DEVICES=1 nohup python -m tmbed predict --batch-size 5000 -f ~/protein/data1.fasta -e ~/protein/data1.h5 -p ~/protein/ch/data1.pred > ~/protein/data1.log 2>&1 &

Finally, thank you very much for your work.

**Comment by BernhoferM** [comment]
Ah, then I misunderstood your issue. I thought that the 7 GB memory of a single GPU were not enough to process your sequences with the ProtT5 encoder and you wanted to combine the memory of multiple GPUs to be able to fit those longer sequences. However, based on your solution, it seems that instead you just wanted to spread the work over all GPUs to speed up the process, i.e., have more compute (not memory).
